window.$ = window.jQuery = require('jquery');
require('bootstrap');
require("./jquery.sticky.js");
require("./jquery.easing.1.3.min.js");
require("./owl.carousel.min.js");
require("./jquery.mask.min.js");
require("./track.js");
require("./app.js");
require("./contact.js");
require("./mask.js");
require("./drift.js");